# Generated by Django 3.2.18 on 2023-03-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='license',
            name='primary_watercourse',
            field=models.ManyToManyField(blank=True, related_name='primary_wc_id', to='main.WaterCourse', verbose_name='Главный водоток'),
        ),
        migrations.AlterField(
            model_name='license',
            name='secondary_watercourse',
            field=models.ManyToManyField(blank=True, related_name='secondary_wc_id', to='main.WaterCourse', verbose_name='Побочный водоток'),
        ),
        migrations.AlterField(
            model_name='license',
            name='used_enginery',
            field=models.TextField(default='Не назначено', null=True, verbose_name='Используемая техника'),
        ),
    ]
