# Generated by Django 3.2.18 on 2023-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencewatercourse',
            name='is_primary',
            field=models.IntegerField(choices=[(0, 'Главный'), (1, 'Побочный')], default=0),
        ),
    ]
