# Generated by Django 3.2.18 on 2023-03-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_licencewatercourse_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='license',
        ),
        migrations.CreateModel(
            name='LineLicenseWaterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.license', verbose_name='Лицензия')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.line', verbose_name='Линия')),
                ('watercourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.watercourse', verbose_name='Водоток')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='lines',
            field=models.ManyToManyField(through='main.LineLicenseWaterCourse', to='main.Line'),
        ),
    ]
