# Generated by Django 3.2.18 on 2023-03-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230322_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='watercourse',
            name='parent_watercourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.watercourse'),
        ),
    ]
