# Generated by Django 3.2.18 on 2023-03-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230323_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenceWaterCourse',
            new_name='LicenseWaterCourse',
        ),
    ]
