# Generated by Django 3.2.18 on 2023-03-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230323_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
