# Generated by Django 3.2.18 on 2023-03-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_layer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='aquifer',
            field=models.BooleanField(default=False, verbose_name='Водоносный слой'),
        ),
        migrations.AddField(
            model_name='layer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='layer',
            name='drilling_stopped',
            field=models.BooleanField(default=False, verbose_name='Бурение остановлено'),
        ),
        migrations.AddField(
            model_name='layer',
            name='sample_obtained',
            field=models.BooleanField(default=False, verbose_name='Проба взята'),
        ),
    ]
