# Generated by Django 3.2.18 on 2023-03-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230325_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.license', verbose_name='Лицензия')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.line', verbose_name='Линия')),
                ('watercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.watercourse', verbose_name='Водоток')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
