# Generated by Django 3.2.18 on 2023-03-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_documentation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Документация', 'verbose_name_plural': 'Документация'},
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.license', verbose_name='Лицензия')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.line', verbose_name='Линия')),
                ('watercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.watercourse', verbose_name='Водоток')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Разрез',
                'verbose_name_plural': 'Разрезы',
            },
        ),
    ]
