# Generated by Django 3.2.18 on 2023-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230408_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='pillar_photo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Фото штаги'),
        ),
    ]
