# Generated by Django 3.2.18 on 2023-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_well_pillar_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='mbu',
        ),
        migrations.RemoveField(
            model_name='license',
            name='pmbou',
        ),
        migrations.AlterField(
            model_name='licensewatercourse',
            name='is_primary',
            field=models.IntegerField(choices=[(0, 'Главный'), (1, 'Побочный')], default=0, verbose_name='Тип водотока (главный - да)'),
        ),
    ]
