# Generated by Django 3.2.18 on 2023-04-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230420_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='watercourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.watercourse', verbose_name='Водоток'),
        ),
    ]
