# Generated by Django 3.2.18 on 2023-05-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20230421_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mine',
            name='well',
        ),
        migrations.AddField(
            model_name='mine',
            name='wells',
            field=models.ManyToManyField(to='main.Well', verbose_name='Скважины'),
        ),
    ]
