# Generated by Django 3.2.18 on 2023-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20230502_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='well',
        ),
        migrations.AddField(
            model_name='documentation',
            name='wells',
            field=models.ManyToManyField(to='main.Well', verbose_name='Скважины'),
        ),
    ]
