# Generated by Django 3.2.18 on 2023-05-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20230503_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='wells',
        ),
        migrations.AddField(
            model_name='documentation',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.well', verbose_name='Скважина'),
        ),
        migrations.AddField(
            model_name='layer',
            name='depth',
            field=models.FloatField(max_length=255, null=True, verbose_name='Глубина'),
        ),
    ]
