# Generated by Django 3.2.18 on 2023-05-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20230505_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImageSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='task_images/', verbose_name='Фотографии задания')),
            ],
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Задание')),
                ('task_image_single', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.taskimagesingle', verbose_name='Фотография задания')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(through='main.TaskImage', to='main.TaskImageSingle', verbose_name='Фотографии к заданию'),
        ),
    ]
